import mysql.connector
conobj=mysql.connector.connect(host="localhost",user="root",passwd="rohan")
cur=conobj.cursor()
cur.execute("use Payroll_Management_System")
try:
    cur.execute("drop table Monthly_Pay_File")
    cur.execute("drop table Employee_Details")
except:
    print("Table doesnt exist")

cur.execute("create table Employee_Details(Employee_Number int auto_increment primary key,Employee_Name varchar(40) not null, Gender char(1) not null, DOB date not null, DOJ date not null)")
cur.execute("insert into Employee_Details(Employee_Name,Gender,DOB,DOJ) values('Advaith','M','1974-09-20','2014-09-20')")
cur.execute("insert into Employee_Details(Employee_Name,Gender,DOB,DOJ) values('Aamir','M','1974-09-19','2014-09-20')")
cur.execute("insert into Employee_Details(Employee_Name,Gender,DOB,DOJ) values('Mithun','M','1974-09-18','2014-09-21')")
cur.execute("insert into Employee_Details(Employee_Name,Gender,DOB,DOJ) values('Shakaib','M','1974-09-17','2014-09-22')")
cur.execute("insert into Employee_Details(Employee_Name,Gender,DOB,DOJ) values('Raahil','M','1974-09-16','2014-09-23')")
cur.execute("insert into Employee_Details(Employee_Name,Gender,DOB,DOJ) values('Aryan','M','1974-09-15','2014-09-24')")
cur.execute("insert into Employee_Details(Employee_Name,Gender,DOB,DOJ) values('Shreyan','M','1974-09-14','2014-09-25')")
conobj.commit()
cur.execute("create table Monthly_Pay_File as (select Employee_Number,Employee_Name from Employee_Details)")
cur.execute("alter table Monthly_Pay_File add Number_of_Days_worked int,add Basic int,add Deductions int")
cur.execute("update Monthly_Pay_File set Number_of_Days_worked=250,Basic=21000,Deductions=1560 where Employee_Number=1")
cur.execute("update Monthly_Pay_File set Number_of_Days_worked=200,Basic=20000,Deductions=1500 where Employee_Number=2")
cur.execute("update Monthly_Pay_File set Number_of_Days_worked=150,Basic=15000,Deductions=1000 where Employee_Number=3")
cur.execute("update Monthly_Pay_File set Number_of_Days_worked=300,Basic=30000,Deductions=2500 where Employee_Number=4")
cur.execute("update Monthly_Pay_File set Number_of_Days_worked=400,Basic=40000,Deductions=4500 where Employee_Number=5")
cur.execute("update Monthly_Pay_File set Number_of_Days_worked=100,Basic=10000,Deductions=500 where Employee_Number=6")
cur.execute("update Monthly_Pay_File set Number_of_Days_worked=20,Basic=2000,Deductions=10 where Employee_Number=7")
conobj.commit()
cur.execute("alter table Monthly_Pay_File add DA int after Basic")
cur.execute("alter table Monthly_Pay_File add HRA int after DA")
cur.execute("alter table Monthly_Pay_File add Conveyance int after HRA")
cur.execute("alter table Monthly_Pay_File add Gross int after Conveyance")
cur.execute("alter table Monthly_Pay_File add Net int")
cur.execute("update Monthly_Pay_File set DA=0.55*Basic,HRA=0.35*Basic,Conveyance=0.15*Basic")
cur.execute("update Monthly_Pay_File set Gross=Basic+DA+HRA+Conveyance")
cur.execute("update Monthly_Pay_File set Net=Gross-Deductions")
conobj.commit()

name=input("Enter the name of the employee: ")
print()
cur.execute('select * from Monthly_Pay_File where Employee_Name="'+name+'"')
(Number,Name,Days,Basic,Deductions,DA,HRA,Conveyance,Gross,Net)=cur.fetchall()[0]
print("Salary slip for month of: August 2020")
print("Employee no.:",Number,"\t\t\t\tEmployee name:",Name)
print("-"*79)
print("Basic\t\t",Basic)
print("DA\t\t",DA)
print("HRA\t\t",HRA)
print("Conveynance\t",Conveyance)
print("Deductions\t",Deductions)
print("-"*79)
print("Gross pay:",Gross,"\t\tNet Pay: ",Net)


empid=input("Enter the employee id")
print()
cur.execute("select Employee_Number,Employee_Name,Designation,Basic, Gross,Deductions,Net where Employee_Number="+empid)
(Employee_Number,Employee_Name,Designation,Basic,Gross,Deductions,Net)=cur.fetchall()
data=cur.fetchall()
print("Salary statement for the month of:February 2007")
print("-"79)
print("Eno\t","Name\t\t","Designation\t","Basic\t\t","Gross\t\t","Deductions\t","Net")
print("-"79)
for i in range(no of records):
    (Employee_Number,Employee_Name,Designation,Basic,Gross,Deductions,Net)=cur.fetchall()[i]
    print(Employee_Name,"\t",Employee_Name,"\t\t",Designation,"\t",Basic,"\t\t",Gross,"\t",Deductions,"\t",Net)
print("-"*79)

